# Style square
set -g status-justify "left"
set -g status-left-length 100
set -g status-right-length 100
set -g status-left "#[bg=magenta,fg=black]  #[bg=magenta,fg=black]#S #[bg=default,fg=colour8] ▪  #{?client_prefix,#[bg=green#,fg=black]  ,#[bg=colour8#,fg=black]  }prefix #[bg=default,fg=white] ▪  "
set -g status-right "#[bg=white,fg=black] #(whoami)@#(uname -n) "
set -g window-status-format "#[bg=default,fg=colour8]#W"
set -g window-status-current-format "#[bg=#{?window_zoomed_flag,yellow,default},fg=blue bold]#W"
