# Style rounding
set -g status-justify "left"
set -g status-left-length 100
set -g status-right-length 100
set -g status-right "#[bg=default,fg=cyan]#[bg=cyan,fg=black]#(whoami)@#(uname -n)#[bg=default,fg=cyan]"
set -g status-left "#[bg=default,fg=magenta]#[bg=magenta,fg=black] #[bg=#{@main},fg=black]#S#[bg=default,fg=magenta]#[bg=default,fg=colour8]  #{?client_prefix,#[bg=default fg=green],#[bg=default fg=colour8]}#{?client_prefix,#[bg=green#,fg=black] ,#[bg=colour8#,fg=black] }prefix#{?client_prefix,#[bg=default fg=green],#[bg=default fg=colour8]}#[bg=default,fg=colour8]  "
set -g window-status-format "#[bg=default,fg=colour8]#W"
set -g window-status-separator " "
set -g window-status-current-format "#[bg=#{?window_zoomed_flag,yellow,default},fg=blue bold]#W"
