# TERMINAL CONFIG
font_family      ZedMono NF
bold_font        auto
italic_font      auto
bold_italic_font auto

# font_features JetBrainsMonoNFM-Regular +calt +clig +liga +ss20 +cv02 +cv03 +cv04 +cv05 +cv06 +cv07 +cv11 +cv14 +cv15 +cv16 +cv17
font_size 17.0
window_padding_width 10
background_opacity 0.8
#adjust_line_height 125%
#modify_font cell_height 125%

# OPEN WINDOW PATH
map ctrl+shift+enter new_window_with_cwd

# CURSOR
shell_integration  no-cursor
cursor_shape beam
cursor_beam_thickness 1.0
cursor_blink_interval 0.5
cursor_trail 3

# Tab bar
#tab_bar_margin_width      10
#tab_bar_margin_height     10 0
# tab_bar_margin_color      #101419
#tab_bar_style             separator
#tab_bar_min_tabs          2
#tab_separator             ""
#tab_bar_edge              top
#tab_title_template        "{fmt.fg._0d1117}{fmt.bg._0d1117}{fmt.fg._04d1f9}{fmt.bg._3fb950}{index}{fmt.fg._04d1f9}{fmt.bg._0d1117} {title[:15] + (title[15:] and '…')} {fmt.fg._3fb950}{fmt.bg._0d1117} "
#tab_title_template        "{fmt.fg._ff7b72}{fmt.bg._0d1117} {index}{fmt.fg._c9d1d9}{fmt.bg._0d1117} {title[:15] + (title[15:] and '…')} "
#active_tab_title_template "{fmt.fg._3fb950}{fmt.bg._0d1117}{fmt.fg._0d1117}{fmt.bg._3fb950}{index}{fmt.fg._0d1117}{fmt.bg._3fb950} {title[:40] + (title[40:] and '…')} {fmt.fg._3fb950}{fmt.bg._0d1117} "
# tab_title_template "{fmt.fg._70a5eb}{fmt.bg.default}{fmt.fg._101419}{fmt.bg._70a5eb}{index} {fmt.fg._b6beca}{fmt.bg._1c252c} {title[:40] + (title[40:] and '…')}{fmt.fg._1c252c}{fmt.bg._0d1117} "
#tab_title_template "{fmt.fg._c5c9c5}{fmt.bg.default}{fmt.fg._0d0c0c}{fmt.bg._c5c9c5}{index} {fmt.fg._b6beca}{fmt.bg._181616} {title[:40] + (title[40:] and '…')}{fmt.fg._181616}{fmt.bg._0d0c0c} "
#active_tab_title_template "{fmt.fg._8a9a7b}{fmt.bg.default}{fmt.fg._0d0c0c}{fmt.bg._8a9a7b}{index} {fmt.fg._b6beca}{fmt.bg._181616} {title[:40] + (title[40:] and '…')}{fmt.fg._181616}{fmt.bg._0d0c0c} "
#active_tab_font_style     normal

#include ./themes/paradise.conf
#include ~/.cache/wal/colors-kitty.conf
include ./themes/sora.conf
