# Get editor completions based on the config schema
# "$schema" = 'https://starship.rs/config-schema.json'

add_newline = false
palette = 'flexoki-dark'

format = """
[╭─](8)$os$username$hostname $directory$git_branch$fill$java$nodejs 
[╰─](8)$character"""

[character]
success_symbol = "[](fg:green)"
error_symbol = "[](fg:red)"

[fill]
symbol = " "

[os]
format = "[](fg:blue)[$symbol](bg:blue fg:black)"
disabled = false

[os.symbols]
Windows = " "
Arch = " "

[username]
format = '[$user](bold fg:black bg:blue)'
show_always = true

[hostname]
ssh_only = false
format = "[@$hostname](bold fg:black bg:blue)[](blue)"
disabled = false

[cmd_duration]
min_time = 0
format = '[](blue)[󱦟 $duration](bold bg:blue fg:black)[ ](blue)'

[directory]
read_only = "  "
style = "bold bg:white fg:black"
truncation_length = 1
# truncation_symbol = "••/"
truncation_symbol = "../"
truncate_to_repo = true
format = '[](white)[ ]($style)[$path]($style)[](white)'

[git_branch]
style = "bg: green"
symbol = "󰘬"
# truncation_length = 4
# truncation_symbol = ""
format = " [](green)[$symbol $branch(:$remote_branch)](bold fg:black bg:green)[](green)"

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[palettes.catppuccin_mocha]
red = "#f38ba8"
green = "#a6e3a1"
blue = "#89b4fa"
black = "#1e1e2e"
white = "#cdd6f4"

[palettes.rose-pine]
black = '#191724'
white = '#e0def4'
blue = '#31748f'
green = '#9ccfd8'
red = '#eb6f92'

[palettes.flexoki-dark]
black = '#100F0F'
white = '#CECDC3'
blue = '#4385BE'
green = '#879A39'
red = '#D14D41'

#0 = Black
#1 = Red
#2 = Green
#3 = Yellow
#4 = Blue
#5 = Magenta
#6 = Cyan
#7 = Light Gray
#8 = Dark Gray (a veces considerado como un gris plomo)
#9 = Light Red
#10 = Light Green
#11 = Light Yellow
#12 = Light Blue
#13 = Light Magenta
#14 = Light Cyan
#15 = White
#
#

[java]
format = '[](red)[$symbol $version](bold fg:black bg:red)[](red)'
version_format = "${raw}"
symbol = ""
disabled = false

[nodejs]
symbol = ""
format = '[](green)[$symbol $version](bold fg:black bg:green)[](green)'
