# Style rounding
set -g status-justify "left"
set -g status-left-length 100
set -g status-right-length 100
# set -g status-right "#[bg=default,fg=white]󰍹 #(whoami)@#(uname -n) "
set -g status-right ""
# set -g status-left "#[bg=magenta,fg=black]  #[bg=magenta,fg=black]#S#{?client_prefix,#[bg=green fg=magenta],#[bg=red fg=magenta]}#{?client_prefix,#[bg=green#,fg=black]  ,#[bg=red#,fg=black]  }prefix#{?client_prefix,#[bg=default fg=green],#[bg=default fg=red]} "
set -g status-left "#[bg=magenta,fg=black]  #[bg=magenta,fg=black]#S #[bg=default,fg=colour8] "
set -g window-status-format "#[bg=default,fg=colour8]#W"
set -g window-status-separator "#[bg=default,fg=colour8] "
set -g window-status-current-format "#[bg=#{?window_zoomed_flag,default,default},fg=#{?window_zoomed_flag,yellow,blue} bold]#W"
