# Style rounding
set -g status-justify "left"
set -g status-left-length 100
set -g status-right-length 100
set -g status-right "#[bg=default,fg=white]󰍹 #(whoami)@#(uname -n)"
set -g status-left "#[bg=default,fg=white] #[bg=default,fg=white,bold]#(tmux display -p '#S' | tr '[:lower:]' '[:upper:]') "
set -g window-status-format "#[bg=default,fg=colour8]#W"
set -g window-status-separator " "
set -g window-status-current-format "#[bg=#{?window_zoomed_flag,default,default},fg=#{?window_zoomed_flag,yellow,blue} bold]#W"
set-option -g status-position bottom
