### LIST OF PLUGINS ###
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'tmux-plugins/tmux-yank'

# Resurrect
set -g @resurrect-dir '~/.config/tmux/resurrect'
set -g @resurrect-strategy-nvim 'session'
set -g @resurrect-capture-pane-contents 'on'

# Continuum
set -g @continuum-restore 'on'
set -g @continuum-save-interval '15'

### STATUS BAR ###
set-option -g status-position top
set -gF status-style "bg=default"

# Theme
source-file ~/.config/tmux/statusbar/style-8.conf

#### GENERAL ###
# Reload tmux config
bind r source-file ~/.config/tmux/tmux.conf \; display "Config reloaded!"

# Terminal & key handling
set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",*:Tc"

# Enable vi mode for copy mode
set-window-option -g mode-keys vi

# Vi-like selection in copy mode
# bind -T copy-mode-vi v send-keys -X begin-selection
# bind -T copy-mode-vi C-v send-keys -X rectangle-toggle
# bind -T copy-mode-vi y send-keys -X copy-selection-and-cancel

# Enable mouse
set -g mouse on

# Windows
# set -g base-index 1
# setw -g pane-base-index 1
# set -g renumber-windows on

# Less lag with Escape/Vim
# set -s escape-time 0
# set -g focus-events on
# set -g assume-paste-time 1
# set -g repeat-time 300

### KEYMAPS ###
# Prefix
unbind C-b
set -g prefix C-Space
bind C-Space send-prefix

# Split
unbind '"'
unbind %
bind \\ split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"

# Toggle zoom
# bind -n M-z resize-pane -Z

# Switch windows#
bind -n M-p previous-window
bind -n M-n next-window

# Move windows
bind -n M-H swap-window -t -1\; select-window -t -1
bind -n M-L swap-window -t +1\; select-window -t +1

# Pane resizing
bind -r h resize-pane -L 5
bind -r j resize-pane -D 5
bind -r l resize-pane -R 5
bind -r k resize-pane -U 5

### VIM-TMUX-NAVIGATOR NOT PLUGIN ###
# is_vim="ps -o state= -o comm= -t '#{pane_tty}' \
#     | grep -iqE '^[^TXZ ]+ +(\\S+\\/)?g?(view|n?vim?x?)(diff)?$'"
#
# bind-key -n 'C-h' if-shell "$is_vim" 'send-keys C-h'  'select-pane -L'
# bind-key -n 'C-j' if-shell "$is_vim" 'send-keys C-j'  'select-pane -D'
# bind-key -n 'C-k' if-shell "$is_vim" 'send-keys C-k'  'select-pane -U'
# bind-key -n 'C-l' if-shell "$is_vim" 'send-keys C-l'  'select-pane -R'
#
# # Para tmux en modo copy
# bind-key -T copy-mode-vi 'C-h' select-pane -L
# bind-key -T copy-mode-vi 'C-j' select-pane -D
# bind-key -T copy-mode-vi 'C-k' select-pane -U
# bind-key -T copy-mode-vi 'C-l' select-pane -R

# Floating window
bind-key -n M-f run-shell '
  CURRENT="#{session_name}"
  # If CURRENT already starts with "float-", leave it as is
  if [ "${CURRENT#float-}" != "$CURRENT" ]; then
      tmux detach-client
  else
      tmux display-popup -d "#{pane_current_path}" -w 80% -h 80% \
          -E "tmux new-session -A -s float-$CURRENT"
  fi
  '

### PANE ###
set -g pane-border-style fg=black
set -g pane-border-lines single
# set -g pane-border-status bottom
# set -g pane-border-format ""
set -g pane-active-border-style fg=green

### Initialize TPM ###
run '~/.config/tmux/plugins/tpm/tpm'
