set -g status-justify "left"
set -g status-left-length 100
set -g status-right-length 100
set -g status-style "bg=yellow,fg=default"
set -g status-left "#[bg=magenta,fg=black]  #[bg=magenta,fg=black]#S #[fg=magenta,bg=colour8] "
set -g status-right "#{?client_prefix,#[fg=green#,bg=default]#[bg=green#,fg=black] PREFIX ,}#[fg=blue,bg=#{?client_prefix,green,default}]#[bg=blue,fg=black] #(whoami)@#(uname -n) "

set -g window-status-separator "#[bg=colour8,fg=black]  "
set -g window-status-format "#[bg=colour8,fg=black]#W#{?window_end_flag,#[fg=default#,bg=colour8] ,}#{?window_end_flag,#[fg=colour8#,bg=default],}"
set -g window-status-current-format "#[bg=colour8,fg=#{?window_zoomed_flag,yellow,white},bold]#W#{?window_end_flag,#[fg=default#,bg=colour8] ,}#{?window_end_flag,#[fg=colour8#,bg=default],}"
